spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: fatec
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format: true
    show-sql: true
